version: "3.2"
services:
  # app container
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    tty: true
    ports:
      - "8765:8765"
    depends_on:
      - db

  db:
    image: mysql
    ports:
      - "3306:3306"
